In [4]:
import pandas as pd 

pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [5]:
pd.Series([1,2,3],index=["Bibek","Saugat","Kritika"])

Bibek      1
Saugat     2
Kritika    3
dtype: int64

In [6]:
data = {
    "names":["Bibek","Saugat","Kritika","Adarsha","Saugat","Prasanna","Rashida","Mandip"],
    'diabetes':[4.0,3.9,3.9,3.3,4.0,3.8,3.9,None]
}

print(data)

df = pd.DataFrame(data)

print(df)

{'names': ['Bibek', 'Saugat', 'Kritika', 'Adarsha', 'Saugat', 'Prasanna', 'Rashida', 'Mandip'], 'diabetes': [4.0, 3.9, 3.9, 3.3, 4.0, 3.8, 3.9, None]}
      names  diabetes
0     Bibek       4.0
1    Saugat       3.9
2   Kritika       3.9
3   Adarsha       3.3
4    Saugat       4.0
5  Prasanna       3.8
6   Rashida       3.9
7    Mandip       NaN

In [7]:
df.head()

     names  diabetes
0    Bibek       4.0
1   Saugat       3.9
2  Kritika       3.9
3  Adarsha       3.3
4   Saugat       4.0

In [8]:
df.head(3)

     names  diabetes
0    Bibek       4.0
1   Saugat       3.9
2  Kritika       3.9

In [9]:
df.tail()

      names  diabetes
3   Adarsha       3.3
4    Saugat       4.0
5  Prasanna       3.8
6   Rashida       3.9
7    Mandip       NaN

In [10]:
df.tail(3)

      names  diabetes
5  Prasanna       3.8
6   Rashida       3.9
7    Mandip       NaN

In [11]:
df.shape

(8, 2)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   names     8 non-null      object
 1   diabetes  7 non-null      float64
dtypes: float64(1), object(1)
memory usage: 256.0+ bytes

In [13]:
df["diabetes"].describe()

count    7.000000
mean     3.828571
std      0.242997
min      3.300000
25%      3.850000
50%      3.900000
75%      3.950000
max      4.000000
Name: diabetes, dtype: float64

In [14]:
df["names"]

0       Bibek
1      Saugat
2     Kritika
3     Adarsha
4      Saugat
5    Prasanna
6     Rashida
7      Mandip
Name: names, dtype: object

In [15]:
df

      names  diabetes
0     Bibek       4.0
1    Saugat       3.9
2   Kritika       3.9
3   Adarsha       3.3
4    Saugat       4.0
5  Prasanna       3.8
6   Rashida       3.9
7    Mandip       NaN

In [16]:
df = df.fillna(3.0)
df

      names  diabetes
0     Bibek       4.0
1    Saugat       3.9
2   Kritika       3.9
3   Adarsha       3.3
4    Saugat       4.0
5  Prasanna       3.8
6   Rashida       3.9
7    Mandip       3.0

In [17]:
df = df.dropna()
df

      names  diabetes
0     Bibek       4.0
1    Saugat       3.9
2   Kritika       3.9
3   Adarsha       3.3
4    Saugat       4.0
5  Prasanna       3.8
6   Rashida       3.9
7    Mandip       3.0

In [18]:
# df.filter()
# iloc
# loc
# groupby